# Generated by Django 5.1.6 on 2025-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
