# Generated by Django 5.1.6 on 2025-02-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_contact_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_otp_expiry',
            new_name='otp_expiry',
        ),
    ]
