# Generated by Django 5.1.6 on 2025-02-14 20:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_contact_otp_expiry_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ngo_logo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.ngo_logo_upload_path),
        ),
    ]
