# Generated by Django 5.1.6 on 2025-02-14 21:35

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_approved_customuser_ngo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ngo_license',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.ngo_license_upload_path),
        ),
    ]
