# Generated by Django 5.1.6 on 2025-02-14 21:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_ngo_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ngo_license',
            field=models.FileField(blank=True, null=True, upload_to=users.models.ngo_license_upload_path, validators=[users.models.validate_ngo_license]),
        ),
    ]
